import { pokemonTypes } from "./PokemonTypes";
export const gradientByType = (color) => `linear-gradient(135deg, ${color} 0%, ${color}88 100%)`;
export const lightTheme = {
    name: "light",
    colors: {
        text: "#1c1c1c",
        textSecondary: "#555555",
        title: "#111111",
        background: "#FFF4E6",
        cardBackground: "#FFF8DC",
        cardBorder: "#FFD699",
        cardShadow: "0 4px 12px rgba(0,0,0,0.1)",
        buttonText: "#333333",
        buttonBackground: gradientByType(pokemonTypes.light.electric),
        buttonHover: gradientByType(pokemonTypes.light.fire),
        link: "#FF8C00",
        linkHover: "#FF6F00",
        badgeText: "#333333",
        badgeBackground: gradientByType(pokemonTypes.light.grass),
        transition: "all 0.3s ease-in-out",
        error: "#FF4D4F",
        success: "#52C41A",
        disabledBg: "#eee",
        disabledText: "#aaa",
        highlight: "#FFD700",
        shadow: "rgba(0,0,0,0.15)",
        border: "#E0E0E0",
    },
    types: pokemonTypes.light,
};
export const darkTheme = {
    name: "dark",
    colors: {
        text: "#ffffff",
        textSecondary: "#000000",
        title: "#FFD700",
        background: "#0B0B0B",
        cardBackground: "#1A1A1A",
        cardBorder: "#333333",
        cardShadow: "0 4px 16px rgba(0,0,0,0.8)",
        buttonText: "#1A1A1A",
        buttonBackground: gradientByType(pokemonTypes.dark.electric),
        buttonHover: gradientByType(pokemonTypes.dark.fire),
        link: "#FFA500",
        linkHover: "#FF8C00",
        badgeText: "#1A1A1A",
        badgeBackground: gradientByType(pokemonTypes.dark.water),
        transition: "all 0.3s ease-in-out",
        error: "#FF4D4F",
        success: "#52C41A",
        disabledBg: "#222",
        disabledText: "#888",
        highlight: "#FFD700",
        shadow: "rgba(255,255,255,0.1)",
        border: "#444",
    },
    types: pokemonTypes.dark,
};
export const themes = { light: lightTheme, dark: darkTheme };
